#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
export GOPATH=$DIR
export PATH=$PATH:/usr/local/go/bin
go get github.com/mattn/go-sqlite3
go get github.com/karrick/godirwalk
go get github.com/pkg/xattr
